### ISSUE TITLE
Merge all DevOps issues into a single board or filter on a board

### ISSUE THREAD

**Issue by will-freshworks** [bcgov/moodle#55]
@will-freshworks is looking for a view of the current DevOps backlog and roadmap

**Comment by kkapoor-fresh** [comment]
@will-freshworks I have added the Perfromance and Learning curators repos to the existing moodle namespace.
![image](https://user-images.githubusercontent.com/77285719/139925222-fadd5a85-4aef-4775-b0c0-500863fdd444.png)

**Comment by kkapoor-fresh** [comment]
@will-freshworks I don't seem to have the access to create new workspaces on Zenhub. Therefore, I have added the github repos for Learning curator and Performance projects to the exiating moodle workspace. You can filter on label Devops to list all related issues for Moodle and Learning Curator. Since I am not working on the Performance project currently, and I will have to go to the Performance workspace and add labels to the closed tickets (if possible) to be able to get the the related issues filtered out, I have just added "devops" label to the epic #122 in Perfromance project so that you can see that as well in the filtered list. 
https://app.zenhub.com/workspaces/moodle-60f098ab875719001bce05fb/board?labels=devops&repos=379226611,406451820,329107952
