### ISSUE TITLE
Warren to test DB and file restore process in TEST

### ISSUE THREAD

**Issue by will-freshworks** [bcgov/moodle#98]

**Comment by warrenchristian1telus** [comment]
@kkapoor-fresh This is basically just a repeat of what I shared on Rocket.Chat.

While testing the recommended restore procedures, I had some issues with the process:

moodle-data PVC can’t be deleted while in use (Status: Terminating… forever)
- Deleted the moodle pod to allow PVC to be deleted
- Manually recreated PVC (moodle-data @ 10Gib)
- Test URL started redirecting to dev (RESOLVED – at least for now)
   - As .env is built in dev, and shared to test & prod, every time a pod is (re)created outside of GH Actions (deploy), it gets dev .env file / vars.
- Restore is impeded by PVC drop / restore (+ env issue) 
  - Restore is also limited to (current) namespace backups – I think we should put them all on a shared (/pre-mounted) drive. Maybe in tools namespace

Moving backups to a shared PVC on tools namespace may be a better option.

 - Consolidate backups so that we can migrate using the same method as restore
  - Currently, dev can’t access / restore prod backups directly, using the method above (which means we’d need two different procedures)
 - I think this will give us more opportunity to reduce backups for dev & test (as they could usually be restored from prod)
 - Another option may be to just cross-mount the PVC’s (keep them the same, but grant access to prod backups from dev + test)
  - Could we make it read-only if dev accesses prod backups? Or can that only be set once per volume? Would hate for a dev incident to possibly impact prod backups.
 - Prod would likely never need to restore from another namespace

**Comment by kkapoor-fresh** [comment]
@warren yoy can take backups across namespaces by referencing the correct dns. Kindly see below. This is a restore of DEV database done using the backup from DEV
![image.png](https://images.zenhubusercontent.com/603e7d017ac89a48774c4630/a3223f88-6c8d-470e-9bc9-ce669b5bca06)

**Comment by kkapoor-fresh** [comment]
@warrenchristian1telus the .env redirection issue has been fixed as part of ticket #91 - Prod redirecting to Dev. Would roll this out ot Prod once validated by Warren.

Also, as suggested ,  for file backups removing the /vendor/moodle/moodledata/filedir folder is a good option to simulate the PVC drop.

Last but not the least, the backup containers in DEV and TEST shouldnt be allowed to access the Prod backups.

**Comment by warrenchristian1telus** [comment]
Database and file restore process has been verified and documented in the test namespace.
